package com.amaral.hometask.config

import com.amaral.hometask.model.Assignee
import com.amaral.hometask.model.FamilyConfig
import com.amaral.hometask.model.Reward
import com.amaral.hometask.model.Task
import com.amaral.hometask.model.TaskFrequency
import com.amaral.hometask.model.TaskType
import com.amaral.hometask.repository.FamilyConfigRepository
import com.amaral.hometask.repository.RewardRepository
import com.amaral.hometask.repository.TaskRepository
import org.springframework.beans.factory.annotation.Value
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.web.servlet.config.annotation.CorsRegistry
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer
import jakarta.annotation.PostConstruct

@Configuration
class CorsConfig(@Value("\${app.frontend-url}") private val frontendUrl: String) : WebMvcConfigurer {
    override fun addCorsMappings(registry: CorsRegistry) {
        registry.addMapping("/api/**")
            .allowedOrigins(frontendUrl, "http://localhost:5173", "http://localhost:3000")
            .allowedMethods("GET", "POST", "PUT", "DELETE", "OPTIONS")
            .allowedHeaders("*")
    }
}

@Configuration
class DataSeeder(
    private val taskRepo: TaskRepository,
    private val rewardRepo: RewardRepository,
    private val familyConfigRepo: FamilyConfigRepository,
    @Value("\${app.family.child1-name:Clara}") private val child1Name: String,
    @Value("\${app.family.child2-name:Bernardo}") private val child2Name: String
) {
    private val log = org.slf4j.LoggerFactory.getLogger(javaClass)

    @PostConstruct
    fun seedData() {
        log.info("Starting seed data initialization...")

        // Seed family config (only if not already set)
        if (!familyConfigRepo.existsById(1L)) {
            log.info("Creating default family config with child1=$child1Name, child2=$child2Name")
            familyConfigRepo.save(FamilyConfig(id = 1L, child1Name = child1Name, child2Name = child2Name))
        }

        if (taskRepo.count() == 0L) {
            val tasks = buildTasks()
            log.info("Seeding ${tasks.size} tasks...")
            taskRepo.saveAll(tasks)
            log.info("Tasks seeded successfully")
        } else {
            log.info("Tasks already exist, skipping seeding")
        }

        if (rewardRepo.count() == 0L) {
            val rewards = buildRewards()
            log.info("Seeding ${rewards.size} rewards...")
            rewardRepo.saveAll(rewards)
            log.info("Rewards seeded successfully")
        } else {
            log.info("Rewards already exist, skipping seeding")
        }

        log.info("Seed data initialization completed")
    }

    /**
     * Punitive model: every task below is worth 0 positive points — completing
     * it correctly and on time is simply the expected baseline. A −1 occurrence
     * is only ever generated by [AssignmentService] (missed deadline, manual
     * penalty for incomplete work, or equipment issue not reported in time).
     *
     * The checklist for each task is embedded in `description` as "- item"
     * lines; the frontend renders these as tickable steps the child must all
     * check before the task can be marked done — a lightweight way to enforce
     * "todos os passos foram feitos" without a separate per-step DB table.
     */
    private fun buildTasks() = listOf(
        Task(
            name = "Aspirador na casa",
            description = "- Passar aspirador em TODAS as áreas coletivas da casa\n" +
                "- Se o filtro estiver cheio, esvaziar\n" +
                "- Se a escova/ponta estiver cheia de cabelos, retirar os cabelos e limpar",
            type = TaskType.DAILY, frequency = TaskFrequency.DAILY,
            defaultAssignee = Assignee.UNASSIGNED,
            points = 0, deadline = "21:00", timeWindow = "Diária", sortOrder = 1
        ),
        Task(
            name = "Limpar o banheiro comum",
            description = "- Passar aspirador no banheiro\n" +
                "- Limpar pia e espelho\n" +
                "- Limpar o vaso sanitário\n" +
                "- Retirar cabelos do box",
            type = TaskType.WEEKLY, frequency = TaskFrequency.WEEKLY,
            defaultAssignee = Assignee.UNASSIGNED,
            points = 0, deadline = "21:00", timeWindow = "Semanal — até domingo 21:00", sortOrder = 2
        ),
        Task(
            name = "Tirar itens pessoais da sala",
            description = "- Retirar TODOS os itens pessoais deixados na sala (meias, calçados, mochilas, roupas...)\n" +
                "- A sala deve ficar sem objetos pessoais ao final da tarefa",
            type = TaskType.RULE, frequency = TaskFrequency.DAILY,
            defaultAssignee = Assignee.UNASSIGNED,
            points = 0, deadline = "20:00", timeWindow = "Diária", sortOrder = 3
        ),
        Task(
            name = "Retirar roupas íntimas do box",
            description = "- Retirar roupas íntimas molhadas do box\n" +
                "- Levar a roupa para o local correto de secagem/lavagem\n" +
                "- Abrir a janela do box\n" +
                "- Fechar a porta do box\n" +
                "(vale sempre que houver banho — até 1h após cada banho)",
            type = TaskType.RULE, frequency = TaskFrequency.DAILY,
            defaultAssignee = Assignee.UNASSIGNED,
            points = 0, deadline = "", timeWindow = "Até 1h após o banho", sortOrder = 4
        ),
        Task(
            name = "Arrumar a mesa — café da manhã",
            description = "- Se a máquina de lavar louça estiver limpa, retirar os itens e guardar\n" +
                "- Colocar na máquina os itens da mesa, fogão e pia\n" +
                "- Conferir a máquina e ligá-la/programá-la\n" +
                "- Limpar os protetores de prato\n" +
                "- Limpar a mesa\n" +
                "- Limpar e organizar as cadeiras",
            type = TaskType.DAILY, frequency = TaskFrequency.DAILY,
            defaultAssignee = Assignee.UNASSIGNED,
            points = 0, deadline = "", timeWindow = "Até 30 min após o café", sortOrder = 5
        ),
        Task(
            name = "Arrumar a mesa — almoço",
            description = "- Se a máquina de lavar louça estiver limpa, retirar os itens e guardar\n" +
                "- Colocar na máquina os itens da mesa, fogão e pia\n" +
                "- Conferir a máquina e ligá-la/programá-la\n" +
                "- Limpar os protetores de prato\n" +
                "- Limpar a mesa\n" +
                "- Limpar e organizar as cadeiras\n" +
                "(o almoço é corrido — esta tarefa é sempre feita pelos dois juntos)",
            type = TaskType.JOINT, frequency = TaskFrequency.DAILY,
            defaultAssignee = Assignee.BOTH,
            points = 0, deadline = "", timeWindow = "Até 30 min após o almoço · sempre em dupla", sortOrder = 6
        ),
        Task(
            name = "Arrumar a mesa — jantar",
            description = "- Se a máquina de lavar louça estiver limpa, retirar os itens e guardar\n" +
                "- Colocar na máquina os itens da mesa, fogão e pia\n" +
                "- Conferir a máquina e ligá-la/programá-la\n" +
                "- Limpar os protetores de prato\n" +
                "- Limpar a mesa\n" +
                "- Limpar e organizar as cadeiras",
            type = TaskType.DAILY, frequency = TaskFrequency.DAILY,
            defaultAssignee = Assignee.UNASSIGNED,
            points = 0, deadline = "", timeWindow = "Até 30 min após o jantar", sortOrder = 7
        ),
        Task(
            name = "Tirar o lixo",
            description = "- Verificar se as lixeiras da casa precisam ser esvaziadas\n" +
                "- Levar o lixo para o local correto",
            type = TaskType.DAILY, frequency = TaskFrequency.EVERY_2_DAYS,
            defaultAssignee = Assignee.UNASSIGNED,
            points = 0, timeWindow = "A cada 2 dias", sortOrder = 8
        ),
    )

    /**
     * Rewards are now an optional, separate positive-reinforcement layer —
     * NOT part of the automatic point/consequence system, which is purely
     * punitive per the house rules. Parents can use these manually if they
     * want to celebrate a clean week (e.g. zero occurrences).
     */
    private fun buildRewards() = listOf(
        Reward(name = "Escolher o filme/jogo do fim de semana", pointsCost = 0, emoji = "🎬"),
        Reward(name = "Escolher o jantar",                       pointsCost = 0, emoji = "🍕"),
        Reward(name = "1 hora extra de tela/música",             pointsCost = 0, emoji = "📱"),
    )
}
