spring.application.name=home-task-service

# ── Database ──────────────────────────────────────────────────────────────────
# Local default: H2 in-memory
spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=postgres
spring.datasource.password=QpXlkybUAcNdGPiNyQosFyFCWuiACBcI
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false

# ── App config ────────────────────────────────────────────────────────────────
app.frontend-url=${FRONTEND_URL:http://localhost:5173}
app.family.child1-name=${CHILD1_NAME:Clara}
app.family.child2-name=${CHILD2_NAME:Bernardo}

server.port=${PORT:8080}

DATABASE_URL=postgresql://shinkansen.proxy.rlwy.net:55734/railway